POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIxQGdtYWlsLmNvbSIsImV4cCI6MTc4NzU4NDUyNiwidXNlcklkIjoyfQ.UkQqXHLDDoATlvIVrhPUhbm1ppSMY9INMCw3vLr5bMI

{
    "name": "Test event",
    "description": "a test event",
    "location": "ho-chi-minh city",
    "date_time": "2026-08-24T11:14:00+07:00"
}