PUT http://localhost:8080/events/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIxQGdtYWlsLmNvbSIsImV4cCI6MTc4NzU5MjQ2NiwidXNlcklkIjoyfQ.-ONTgabfQUAVWBlRpEZ0Rd-WyRQbEgNaM3ZQNK44f7c

{
    "name": "Test event update",
    "description": "a test event update",
    "location": "buon ma thuot",
    "date_time": "2026-08-24T11:14:00+07:00"
}